name: journal
description: "Nucleon's great Journal Application."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.2+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Design
  flutter_feather_icons: ^2.0.0+1   # https://pub.dev/packages/flutter_feather_icons
  flutter_svg: ^2.2.0               # https://pub.dev/packages/flutter_svg
  flutter_acrylic: ^1.1.4           # https://pub.dev/packages/flutter_acrylic
  flutter_animate: ^4.5.2           # https://pub.dev/packages/flutter_animate

  # Functional
  intl: ^0.20.2                 # https://pub.dev/packages/intl
  window_manager: ^0.5.0        # https://pub.dev/packages/window_manager  
  collection: ^1.19.1           # https://pub.dev/packages/collection
  provider: ^6.1.5              # https://pub.dev/packages/provider
  tuple: ^2.0.2                 # https://pub.dev/packages/tuple
  
  # Features
  markdown: ^7.3.0              # https://pub.dev/packages/markdown
  markdown_widget: ^2.3.2+8     # https://pub.dev/packages/markdown_widget
  flutter_math_fork: ^0.7.4     # https://pub.dev/packages/flutter_math_fork
  pinput: ^5.0.1                # https://pub.dev/packages/pinput

  # Encryption
  encrypt: ^5.0.3               # https://pub.dev/packages/encrypt
  pointycastle: ^3.9.1          # https://pub.dev/packages/pointycastle version is dependency of encrypt

  nucleon:
    git:
      url: https://github.com/LennartSchuermann/nucleondesign
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.svg
    - assets/images/ellipse.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
